apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: bottlerocket
spec:
  amiFamily: Bottlerocket
  role: karpenterNodeRole-eksworkshop-eksctl
  securityGroupSelectorTerms:
  - tags:
      alpha.eksctl.io/cluster-name: eksworkshop-eksctl
  subnetSelectorTerms:
  - tags:
      alpha.eksctl.io/cluster-name: eksworkshop-eksctl
  tags:
    managed-by: "karpenter"
    intent: "apps"