apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: ubuntu-nt
spec:
  amiFamily: Ubuntu
  role: karpenterNodeRole-eksworkshop-eksctl
  amiSelectorTerms:
    - id: ami-08ba1ec427b0a2f74
  securityGroupSelectorTerms:
  - tags:
      alpha.eksctl.io/cluster-name: eksworkshop-eksctl
  subnetSelectorTerms:
  - tags:
      alpha.eksctl.io/cluster-name: eksworkshop-eksctl
  tags:
    managed-by: "karpenter"
    intent: "apps"