apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: weighted-provisioner-ri
spec:
  providerRef:
    name: weight-provisioner-ri
  ttlSecondsAfterEmpty: 5
  labels:
    type: karpenter
  weight: 2
  requirements:
  - key: "node.kubernetes.io/instance-type"
    operator: In
    values: ["c4.large"]
  limits:
    resources:
      cpu: "100"
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
  securityGroupSelector:
    karpenter.sh/discovery: "${CLUSTER_NAME}" # replace with your cluster name
